function randomID() {
  return Math.floor(Math.random() * 1000);
}
const data = [
  {
    title: "Testing api with valid data",
    bookingdates: {
      checkin: "2023-05-01",
      checkout: "2023-05-05",
    },
    depositpaid: true,
    firstname: "Alice",
    lastname: "Smith",
    roomid: 789,
    email: "alice.smith@example.com",
    phone: "+1-123-456-7890",
    expectedCode: 201,
    errorMessage: null,
  },
  {
    title: "Testing api without passing firstname value",
    bookingdates: {
      checkin: "2023-05-01",
      checkout: "2023-05-05",
    },
    depositpaid: false,
    firstname: "",
    lastname: "Maluleke",
    roomid: 456,
    email: "tadaa@gmail.com",
    phone: "+278945654662",
    expectedCode: 400,
    errorMessage: "First name may not be blank",
  },
  {
    title: "Testing api with duplicate id",
    bookingdates: {
      checkin: "2023-05-01",
      checkout: "2023-05-05",
    },
    depositpaid: false,
    firstname: "Tshepo",
    lastname: "Maluleke",
    roomid: 123,
    email: "tadaa@gmail.com",
    phone: "+278945654662",
    expectedCode: 409,
    errorMessage: null,
  },
  {
    title: "Testing api without passing email value",
    bookingdates: {
      checkin: "2023-05-01",
      checkout: "2023-05-05",
    },
    depositpaid: true,
    firstname: "John",
    lastname: "Doe",
    roomid: 234,
    email: "",
    phone: "+278945654662",
    expectedCode: 400,
    errorMessage: "Email may not be blank",
  },
  {
    title: "Testing api without passing phone value",
    bookingdates: {
      checkin: "2023-05-01",
      checkout: "2023-05-05",
    },
    depositpaid: true,
    firstname: "Jane",
    lastname: "Doe",
    roomid: 345,
    email: "jane.doe@example.com",
    phone: "",
    expectedCode: 400,
    errorMessage: "Phone may not be blank",
  },
  {
    title: "Testing api with invalid email format",
    bookingdates: {
      checkin: "2023-05-01",
      checkout: "2023-05-05",
    },
    depositpaid: false,
    firstname: "Bob",
    lastname: "Smith",
    roomid: 567,
    email: "bob.smith@",
    phone: "+278945654662",
    expectedCode: 400,
    errorMessage: "Enter a valid email address",
  },

  {
    title: "Testing api with invalid checkin date format",
    bookingdates: {
      checkin: "2023/05/01",
      checkout: "2023-05-05",
    },
    depositpaid: false,
    firstname: "John",
    lastname: "Doe",
    roomid: 2,
    email: "johndoe@example.com",
    phone: "+1-234-567-8901",
    expectedCode: 400,
    errorMessage: "Invalid date format for checkin",
  },

  {
    title: "Testing api with invalid checkout date format",
    bookingdates: {
      checkin: "2023-05-01",
      checkout: "2023/05/05",
    },
    depositpaid: false,
    firstname: "Jane",
    lastname: "Doe",
    roomid: 3,
    email: "janedoe@example.com",
    phone: "+1-345-678-9012",
    expectedCode: 400,
    errorMessage: "Invalid date format for checkout",
  },

  {
    title: "Testing api with checkout date before checkin date",
    bookingdates: {
      checkin: "2023-05-05",
      checkout: "2023-05-01",
    },
    depositpaid: true,
    firstname: "Bob",
    lastname: "Johnson",
    roomid: 4,
    email: "bobjohnson@example.com",
    phone: "+1-456-789-0123",
    expectedCode: 400,
    errorMessage: "Checkout date must be after checkin date",
  },

  {
    title: "Testing api with invalid email format",
    bookingdates: {
      checkin: "2023-05-01",
      checkout: "2023-05-05",
    },
    depositpaid: true,
    firstname: "Samantha",
    lastname: "Lee",
    roomid: 5,
    email: "samanthaleeexample.com",
    phone: "+1-567-890-1234",
    expectedCode: 400,
    errorMessage: "Invalid email format",
  },

  {
    title: "Testing api with invalid phone number format",
    bookingdates: {
      checkin: "2023-05-01",
      checkout: "2023-05-05",
    },
    depositpaid: true,
    firstname: "David",
    lastname: "Nguyen",
    roomid: 6,
    email: "davidnguyen@example.com",
    phone: "1234567890",
    expectedCode: 400,
    errorMessage: "Invalid phone number format",
  },

  {
    title: "Testing api with missing depositpaid field",
    bookingdates: {
      checkin: "2023-05-01",
      checkout: "2023-05-05",
    },
    firstname: "Amanda",
    lastname: "Tran",
    roomid: 7,
    email: "amandatran@example.com",
    phone: "+1-678-901-2345",
    expectedCode: 400,
    errorMessage: "Missing required field: depositpaid",
  },
  {
    title: "Testing api with invalid check-in date format",
    bookingdates: {
      checkin: "2023/05/01",
      checkout: "2023-05-05",
    },
    depositpaid: true,
    firstname: "John",
    lastname: "Doe",
    roomid: randomID(),
    email: "johndoe@example.com",
    phone: "+1-123-456-7890",
    expectedCode: 400,
    errorMessage:
      "Invalid date format. Date should be in the format YYYY-MM-DD",
  },
  {
    title: "Testing api with invalid checkout date format",
    bookingdates: {
      checkin: "2023-05-01",
      checkout: "2023/05/05",
    },
    depositpaid: true,
    firstname: "John",
    lastname: "Doe",
    roomid: randomID(),
    email: "johndoe@example.com",
    phone: "+1-123-456-7890",
    expectedCode: 400,
    errorMessage:
      "Invalid date format. Date should be in the format YYYY-MM-DD",
  },
  {
    title: "Testing api with past check-in date",
    bookingdates: {
      checkin: "2022-12-31",
      checkout: "2023-01-01",
    },
    depositpaid: true,
    firstname: "John",
    lastname: "Doe",
    roomid: randomID(),
    email: "johndoe@example.com",
    phone: "+1-123-456-7890",
    expectedCode: 400,
    errorMessage: "Check-in date must be a future date",
  },
  {
    title: "Testing api with check-in date after checkout date",
    bookingdates: {
      checkin: "2023-05-05",
      checkout: "2023-05-01",
    },
    depositpaid: true,
    firstname: "John",
    lastname: "Doe",
    roomid: randomID(),
    email: "johndoe@example.com",
    phone: "+1-123-456-7890",
    expectedCode: 400,
    errorMessage: "Check-out date must be after check-in date",
  },
  {
    title: "Testing api with invalid email format",
    bookingdates: {
      checkin: "2023-05-01",
      checkout: "2023-05-05",
    },
    depositpaid: true,
    firstname: "John",
    lastname: "Doe",
    roomid: randomID(),
    email: "johndoeexample.com",
    phone: "+1-123-456-7890",
    expectedCode: 400,
    errorMessage: "Invalid email format",
  },
];

export default data;
