const data = [
  {
    title: "Testing api with valid data",
    name: "Tshepo Maluleke",
    email: "tshepo@gmail.com",
    phone: "+2787675456782",
    subject: "Testing the api",
    description: "Testing the api for sending message.",
    expectedCode: 201,
    errorMessage: null,
  },
  {
    title: "Testing api without passing email value",
    name: "Tshepo Maluleke",
    email: "",
    phone: "+2787675456782",
    subject: "Testing the api",
    description: "Testing the api for sending message.",
    expectedCode: 400,
    errorMessage: "Email may not be blank",
  },
  {
    title: "Testing api with invalid phone number",
    name: "John Doe",
    email: "johndoe@example.com",
    phone: "1234",
    subject: "Testing the api",
    description: "Testing the api for sending message.",
    expectedCode: 400,
    errorMessage: "Invalid phone number",
  },
  {
    title: "Testing api with missing subject",
    name: "Jane Smith",
    email: "janesmith@example.com",
    phone: "+27871234567",
    subject: "",
    description: "Testing the api for sending message.",
    expectedCode: 400,
    errorMessage: "Subject may not be blank",
  },
  {
    title: "Testing api with long subject",
    name: "Alice Brown",
    email: "alice@example.com",
    phone: "+27871234568",
    subject:
      "This is a very long subject line that exceeds the maximum length allowed by the API",
    description: "Testing the api for sending message.",
    expectedCode: 400,
    errorMessage: "Subject may not be greater than 100 characters",
  },
  {
    title: "Testing api with long description",
    name: "Bob Green",
    email: "bob@example.com",
    phone: "+27871234569",
    subject: "Testing the api",
    description:
      "This is a very long description that exceeds the maximum length allowed by the API. This text should be long enough to trigger an error message.",
    expectedCode: 400,
    errorMessage: "Description may not be greater than 1000 characters",
  },
  {
    title: "Testing api with invalid email",
    name: "Charlie Blue",
    email: "charlie@example",
    phone: "+27871234570",
    subject: "Testing the api",
    description: "Testing the api for sending message.",
    expectedCode: 400,
    errorMessage: "Enter a valid email address",
  },
  {
    title: "Testing api with invalid phone number format",
    name: "David Red",
    email: "david@example.com",
    phone: "1234",
    subject: "Testing the api",
    description: "Testing the api for sending message.",
    expectedCode: 400,
    errorMessage: "Invalid phone number format",
  },
  {
    title: "Testing api with invalid name characters",
    name: "John123 Doe",
    email: "johndoe@example.com",
    phone: "+27871234567",
    subject: "Testing the api",
    description: "Testing the api for sending message.",
    expectedCode: 400,
    errorMessage: "Name may only contain letters, spaces, and hyphens",
  },
  {
    title: "Testing api with missing name",
    name: "",
    email: "johndoe@example.com",
    phone: "+27871234567",
    subject: "Testing the api",
    description: "Testing the api for sending message.",
    expectedCode: 400,
    errorMessage: "Name may not be blank",
  },
  {
    title: "Testing api with special characters in description",
    name: "Jenny Smith",
    email: "jennysmith@example.com",
    phone: "+27871234568",
    subject: "Testing the api",
    description:
      "This description contains special characters like @, #, $, %, ^, &, *, (, ), etc.",
    expectedCode: 201,
    errorMessage: null,
  },
  {
    title: "Testing api with special characters in subject",
    name: "Michael Johnson",
    email: "michael@example.com",
    phone: "+27871234569",
    subject:
      "This subject contains special characters like @, #, $, %, ^, &, *, (, ), etc.",
    description: "Testing the api for sending message.",
    expectedCode: 201,
    errorMessage: null,
  },
  {
    title: "Testing api with emojis in description",
    name: "Alice Green",
    email: "alice@example.com",
    phone: "+27871234570",
    subject: "Testing the api",
    description: "This description contains emojis like 😃, 🚀, 🌞, 🌈, etc.",
    expectedCode: 201,
    errorMessage: null,
  },
  {
    title: "Testing api with emojis in subject",
    name: "Bob Blue",
    email: "bob@example.com",
    phone: "+27871234571",
    subject: "This subject contains emojis like 🎉, 🎁, 🎂, 🎊, etc.",
    description: "Testing the api for sending message.",
    expectedCode: 201,
    errorMessage: null,
  },
];

export default data;
